### ISSUE TITLE
Conflict with property "scope"

### ISSUE THREAD

**Issue by turkelinda** [rse/style-scope#1]
There are other libraries or frameworks (e.g. VueJS) that uses "scope" as a property in a HTML-Tag.
e.g.
<template scope="scope"></template>
and this is in conflict with the scope property of this style-scope module.
There could be this solutions:
- the scope property of this module can be set in a config, e.g. as "gs-scope" (for Gemstone)
- make it possible to exclude specific tags in a config, e.g. the tag "tamplate"
- ignore the scope property on all tags except the root-tag (-> maybe thats not the best solution, maybe the scope property is needed as well on not-root-tags?)

**Comment by rse** [comment]
Good catch. The solution to name the property differently from "scope" was already supported and as an additional forth solution I've now implemented to possibility to "escape" directives. You can now use `<template scope-esc="foo">` in Vue to get `<template scope="foo">`.
